# GET https://api.spotify.com/v1/me/
#     Content-Type: "application/json"
#     Accept: "application/json"
#     Authorization: "Bearer BQCVeRJrktm8BUr9p1UwAa1BLUi29SJrtxUsBMLT-75TfFqj9LBlbIH77PFUE3Br-IpA9JXlCNmbnik5hc1BOvfSgmLH0O2ldNG0VhBp9kjUJ_5-hYDfpMiqFGkD057up49tDIty5x_35iQQnJONsxYHOVvK6mN5fDaNsjQ85g"


# GET http://localhost:8888/getLeaderboard/

POST http://localhost:8888/createRandomUsers/2